use inc::Module::JSAN::DSL;

name            ExtX.Layout

version         0.01
author          'Nickolay (SamuraiJack) Platonov <root@symbie.org>'

abstract        'Collection of layouts for ExtJS'
license         lgpl


requires        Joose                           3.01
requires        JooseX.Bridge.Ext               0.01
requires        Task.ExtJS                      3.100.000
requires        JooseX.Namespace.Depended       0.01

test_requires   Test.Run                        0.03

docs_markup     mmd